#!/bin/bash

hermes_home=~/.hermes/
database_name=${hermes_home}.db

hermes_default () {
	if [ -f $database_name ]; then
		echo "Hermes exists at: "
		cat $database_name
		echo
		echo "RUNNING $1"
		echo "================"
		hermes_run $@
	else
		echo "Not found. Please \`hermes init\`"
	fi
}

hermes_ls() {
	# find file
	for d in ${hermes_home}*/scripts/ ; do
		echo "================"
		echo `basename $(dirname $d)`
		echo "================"
		ls -1 $d
	done
	echo 
}

hermes_run() {
	# find file
	for d in ${hermes_home}*/scripts/ ; do
		if [[ -f ${d}${1} ]]; then
			hermes_file=${d}${1}
		fi
	done

	if [[ -f ${hermes_file} ]]; then
		# make sure it can run
		# echo ${hermes_file}
		chmod +x ${hermes_file}
		shift
		(cd /; .${hermes_file} $@)
	else
		echo "Script {${1}} is not found";
	fi
}

hermes_status() {
	echo "nada"
}

hermes_use () {
	git ls-remote "$2" &>/dev/null
	if [ "$?" -ne 0 ]; then
		echo "[ERROR] Unable to read from '$database_new'"
		exit 1;
	fi

	if [ $# -gt 2 ]; then
		gitname=$3
	else 
		gitbase=`basename $2`
		gitname="${gitbase%.*}"
	fi

	git clone $2 ${hermes_home}$gitname
}

case $1 in
	ls) hermes_ls ;;
	run) shift; hermes_run $@;;
	status) hermes_status ;;
	use) hermes_use $@ ;;
	*) hermes_default $@
esac

